{"name":"Тест активации абонента","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.lang.ExceptionInInitializerError","trace":"java.lang.ExceptionInInitializerError\r\n\tat steps.AuthSteps.postLoginRequest(AuthSteps.java:15)\r\n\tat base.BaseTest.login(BaseTest.java:15)\r\n\tat YotaTests.subscriberActivationTest(YotaTests.java:17)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:639)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:774)\r\n\tat org.testng.TestRunner.run(TestRunner.java:624)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:359)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:261)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1140)\r\n\tat org.testng.TestNG.run(TestNG.java:1048)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: java.lang.UnsupportedOperationException: Can't convert 'file:D:\\MMTPtesttask\\src\\main\\resources\\resources.properties' to a valid URI\r\n\tat org.aeonbits.owner.Util.unsupported(Util.java:124)\r\n\tat org.aeonbits.owner.PropertiesManager.toURIs(PropertiesManager.java:134)\r\n\tat org.aeonbits.owner.PropertiesManager.<init>(PropertiesManager.java:105)\r\n\tat org.aeonbits.owner.DefaultFactory.create(DefaultFactory.java:43)\r\n\tat org.aeonbits.owner.ConfigFactory.create(ConfigFactory.java:66)\r\n\tat service.Specification.<clinit>(Specification.java:12)\r\n\t... 26 more\r\nCaused by: java.net.URISyntaxException: Illegal character in opaque part at index 7: file:D:\\MMTPtesttask\\src\\main\\resources\\resources.properties\r\n\tat java.net.URI$Parser.fail(URI.java:2847)\r\n\tat java.net.URI$Parser.checkChars(URI.java:3020)\r\n\tat java.net.URI$Parser.parse(URI.java:3057)\r\n\tat java.net.URI.<init>(URI.java:588)\r\n\tat org.aeonbits.owner.ConfigURIFactory.newURI(ConfigURIFactory.java:39)\r\n\tat org.aeonbits.owner.PropertiesManager.toURIs(PropertiesManager.java:130)\r\n\t... 30 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1702906446546,"stop":1702906447153,"uuid":"19c9f4af-47b8-4643-871a-f47dd950ff70","historyId":"f6cd9dce3e80c662fa013753d4aea815","fullName":"YotaTests.subscriberActivationTest","labels":[{"name":"package","value":"YotaTests"},{"name":"testClass","value":"YotaTests"},{"name":"testMethod","value":"subscriberActivationTest"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"MMTPtesttask"},{"name":"subSuite","value":"YotaTests"},{"name":"host","value":"LAPTOP-425AQ0SR"},{"name":"thread","value":"8196@LAPTOP-425AQ0SR.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"epic","value":"Тестовое задание Yota"}],"links":[]}